# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Programming/Projects/CNN-on-FPGA/CNN.srcs/sources_1/ip/lilMem/lilMem.xci
# IP: The module: 'lilMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programming/Projects/CNN-on-FPGA/CNN.srcs/sources_1/ip/lilMem/lilMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lilMem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Programming/Projects/CNN-on-FPGA/CNN.srcs/sources_1/ip/lilMem/lilMem.xci
# IP: The module: 'lilMem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Programming/Projects/CNN-on-FPGA/CNN.srcs/sources_1/ip/lilMem/lilMem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lilMem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
